Repository perawallet/connect, pull requests merged in 2022-11, with the labels that each got.

#57 feat(connect): keep websocket alive on safari
  src/modal/section/pending-message/PeraWalletConnectModalPendingMessage.ts
  src/modal/section/pending-message/util/peraWalletConnectModalPendingMessageConstants.ts
Labels: Ready for review

#59 feat(v1): add network mismatch
  src/PeraWalletConnect.ts
  src/modal/_pera-wallet-modal.scss
  src/modal/sign-txn/_pera-wallet-sign-txn-modal.scss
  src/util/PeraWalletConnectError.ts
  src/util/network/teller/appTellerManager.ts
  src/util/peraWalletTypes.ts
Labels: Ready for review

#54 feat(web-wallet): add feature flagging
  package-lock.json
  package.json
  src/PeraWalletConnect.ts
  src/modal/PeraWalletConnectModal.ts
  src/modal/mode/desktop/PeraWalletConnectModalDesktopMode.ts
  src/modal/mode/desktop/_pera-wallet-connect-modal-desktop-mode.scss
  src/modal/mode/touch-screen/PeraWalletModalTouchScreenMode.ts
  src/modal/peraWalletConnectModalUtils.ts
  src/modal/section/pending-message/PeraWalletConnectModalPendingMessage.ts
  src/util/api/peraWalletConnectApi.ts
  src/util/peraWalletConstants.ts
  src/util/storage/storageConstants.ts
  src/util/storage/storageUtils.ts
Labels: Ready for review

#62 v1: Update Readme
  README.md
  src/PeraWalletConnect.ts
  src/util/peraWalletTypes.ts
Labels: Ready for review

#63 chore: Update `algosdk` version
  package-lock.json
  package.json
Labels: Ready for review

#61 feat(sign-txn/modal): throw error after close modal
  src/PeraWalletConnect.ts
  src/modal/header/PeraWalletModalHeader.ts
Labels: Ready for review

#60 fix(connect): try to solve new tab openning issue
  src/PeraWalletConnect.ts
  src/util/dom/domUtils.ts
  src/util/network/teller/Teller.ts
  src/util/network/teller/tellerTypes.d.ts
Labels: Ready for review

#65 fix(sign-txn): throw error after user close tab
  src/PeraWalletConnect.ts
  src/modal/header/PeraWalletModalHeader.ts
  src/modal/peraWalletConnectModalUtils.ts
  src/util/PeraWalletConnectError.ts
Labels: Ready for review

#66 fix: disable cache for config
  src/util/api/peraWalletConnectApi.ts
Labels: Ready for Release, Ready for review

#64 fix: Enable feature flagging
  src/util/api/peraWalletConnectApi.ts
Labels: Ready for Release

#71 fix: solve small issues and add callback for config
  package-lock.json
  package.json
  src/App.ts
  src/PeraWalletConnect.ts
  src/asset/img/PeraWalletDownloadQRCode.png
  src/modal/mode/desktop/PeraWalletConnectModalDesktopMode.ts
  src/modal/mode/desktop/_pera-wallet-connect-modal-desktop-mode.scss
  src/modal/mode/desktop/download-qr-code/PeraWalletDownloadQRCode.ts
  src/modal/mode/desktop/download-qr-code/_pera-wallet-download-qr-code.scss
  src/modal/peraWalletConnectModalUtils.ts
  src/util/api/peraWalletConnectApi.ts
  src/util/api/peraWalletConnectApiTypes.ts
  src/util/peraWalletConstants.ts
Labels: Ready for review

#75 fix(sign-txn): add missing fields to transaction
  src/PeraWalletConnect.ts
  src/util/model/peraWalletModels.ts
Labels: Ready for Release

#76 fix: Resolve `reconnectSession` correctly
  src/PeraWalletConnect.ts
Labels: Ready for Release

#78 fix(disconnect): `reject` with correct error type
  src/PeraWalletConnect.ts
  src/util/PeraWalletConnectError.ts
Labels: Ready for review

#79 perawallet/connect@1.0.5
  package-lock.json
  package.json
  src/PeraWalletConnect.ts
  src/util/PeraWalletConnectError.ts
Labels: Ready for Release

#80 feat: Accept `network` on `connect`
  README.md
  src/PeraWalletConnect.ts
Labels: Ready for review

#81 perawallet/connect@1.0.6
  README.md
  package-lock.json
  package.json
  src/PeraWalletConnect.ts
Labels: Ready for Release
